export const urls = [
  'https://thomasjfrank.com/notion-formula-cheat-sheet',
  'https://thomasjfrank.com/notion-databases-the-ultimate-beginners-guide',
  'https://thomasjfrank.com/notion-automation-youtube-data',
  'https://thomasjfrank.com/notion-automated-recurring-tasks',
  'https://thomasjfrank.com/notion-api-crash-course',
  'https://thomasjfrank.com/how-to-create-and-edit-notion-pages-notion-fundamentals',
  'https://thomasjfrank.com/a-guide-to-editing-and-formatting-text-in-notion-notion-fundamentals',
  'https://thomasjfrank.com/notion-blocks-guide',
  'https://thomasjfrank.com/how-to-build-a-personal-dashboard-in-notion',
  'https://thomasjfrank.com/how-to-create-multi-column-layouts-in-notion',
  'https://thomasjfrank.com/notion-links',
  'https://thomasjfrank.com/notion-databases-the-ultimate-beginners-guide',
  'https://thomasjfrank.com/notion-api-crash-course',
];
